name: Refresh REDAME badge img caches

on:
  # push:
  # branches: [main, master]
  schedule:
    - cron: '10 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bash script
        run: bash tools/refresh_img_cache.sh antyuntyuntyun/antyuntyuntyun
