name: Refresh REDAME badge img caches

on:
  push:
    branches: [main, master]
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: sh tools/refresh_img_cache.sh
