name: Update Tech blog feed snippet

on:
  push:
    branches: [main, master]
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    # - cron: '1 0 * * *'
    # At 10:00.(JST) → At 01:00.(UTC)
    # 0 1 * * *でよいはずだがずれるので更に50分前に設定
    - cron: "10 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install feedsnippet
        run: go install github.com/ikawaha/feedsnippet@latest

      - name: Update README.md
        run: feedsnippet -config feedsnippet.yml -file README.md

      - name: git commit
        run: |
          git config --local user.email "56618795+antyuntyuntyun@users.noreply.github.com"
          git config --local user.name "antyuntyuntyun"
          git add README.md
          git commit -m "Update feed snippet: `date +'%Y-%m-%d %H:%M:%S'`"
          git push origin main
